name = input("Enter your name : ")
#result = len(name)
#result = name.find("o")
#print(result)
#result = name.find("s")
#result = name.rfind("l")
name = name.isalpha()
#name = name.isdigit()
#name = name.isupper()
#name = name.capitalize()
#name = name.count("a")
#name = name.replace(" ", "-")
#name = name.upper()
#name.
print(name)
