# name = input("Enter your name : ")
phone_number = input("Enter your phone number : ")
# result = len(name)
# result = name.find("y")
# result = name.rfind("a")
# name = name.capitalize()
# name = name.upper()
# name = name.lower()
# name = name.isdigit()
# name = name.isalpha()
phone_number = phone_number.replace("-","")
print(phone_number)